[server]
maxUploadSize = 2048

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0f172a"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"
